apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::357978613822:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::357978613822:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8UN3YZJAHHHA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-09T07:07:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1228"
  uid: 6d833d1e-d470-4fec-b6ed-a69fe122eb69
