apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::357978613822:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::357978613822:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JVWW2P0XVTVU
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-09T10:11:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1520"
  uid: 9c622d55-99d0-4a2c-b566-7781d37f7cbe
